### PR TITLE
Bun — A Simple fast all-in-one JavaScript - v1

### PR DESCRIPTION
**Pull request by axif0**
**Description:**

This PR adds a fully functional Bun-based HTTP server showcasing:

- **Dynamic Routing:** `/`, `/about`, and `/api/data` routes.
- **Template Rendering (EJS):** Renders `index`, `about`, and `error` pages.
- **Static Assets:** Serves files from `public/`.
- **Logging & Middleware:** Logs requests to `access.log`.
- **Error Handling:** Custom 404 page.

### CODE REVIEW

**Comment by mojafa** [comment]
@axif0 please sign your commits to pass DCO check.

 Amend your last commit to include the sign-off: `git commit --amend --signoff` then  `git push --force`

**Comment by axif0** [comment]
Sorry for the extra commits. @mojafa

**Comment by axif0** [comment]
Could I improve the code more my adding new functionalists after merging this PR? In that case, Kindly can you suggest some ideas?

**Review by idagelic — APPROVED** [review]
@axif0 Nice work, please open up a PR for index.json in the main repo now. Don't forget to signoff the commit

**Pull request merged**
